[package]
name = "herdr-deck-sim"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
publish.workspace = true
description = "Desktop simulator for the herdr-deck UI"

[dependencies]
minifb = "0.28.0"
herdr-deck-render = { path = "../herdr-deck-render" }
