[package]
name = "pixbar-sim"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
publish.workspace = true
description = "Desktop simulator for the pixbar UI"

[dependencies]
minifb = "0.28.0"
pixbar-render = { path = "../pixbar-render" }
